services:
  postgres:
    image: postgres:17
    container_name: eduflow-postgres
    environment:
      POSTGRES_DB: EduFlow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - eduflow-postgres-data:/var/lib/postgresql/data

volumes:
  eduflow-postgres-data:
